src/main/java/de/samply/mdr/gui/beans/AbstractWizard.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package  de.samply.mdr.gui.beans;

import de.samply.mdr.gui.WizardStep;
import java.io.Serializable;
import java.util.List;

/**
 * An abstract Wizard Helper class.
 *
 * @author paul
 */
public abstract class AbstractWizard implements Serializable {

  private static final long serialVersionUID = 1L;

  /** Returns all available steps in this wizard, used for the wizard status bar. */
  public abstract List<WizardStep> getSteps();

  /**
   * Returns all available steps in this wizard, used for the wizard status bar. The argument is
   * used to determine the already completed steps.
   */
  public List<WizardStep> getSteps(String view) {
    List<WizardStep> target = getSteps();

    int step = 1;
    boolean found = false;

    for (WizardStep s : target) {
      if (s.getHref().contains(view)) {
        found = true;
      }

      if (!found) {
        ++step;
      }
    }

    int index = 1;
    for (WizardStep s : target) {
      if (index < step) {
        s.setComplete(true);
        s.setActive(false);
      } else if (index == step) {
        s.setComplete(false);
        s.setActive(true);
      } else {
        s.setComplete(false);
        s.setActive(false);
      }

      s.setLast(false);

      index++;
    }

    target.get(target.size() - 1).setLast(true);

    return target;
  }

  /**
   * Returns true if the given viewId is the first step in this wizard.
   *
   * @param viewId the current viewId (view.viewId)
   * @return true if the given view is the first step in this wizard.
   */
  public Boolean isFirstStep(String viewId) {
    return getSteps().get(0).getHref().contains(viewId);
  }

  /**
   * Returns true if the given viewId is the last step in this wizard.
   *
   * @param viewId the current viewId (view.viewId)
   * @return true if the given view is the last step in this wizard.
   */
  public Boolean isLastStep(String viewId) {
    return getSteps().get(getSteps().size() - 1).getHref().contains(viewId);
  }

  /**
   * Returns to the previous step. If the current step can not be found in the list of available
   * steps, it returns null
   */
  public String previousStep(String viewId) {
    int index = 0;

    List<WizardStep> steps = getSteps();

    for (WizardStep s : steps) {
      if (s.getHref().contains(viewId) && index != 0) {
        return steps.get(index - 1).getHref().get(0) + "?faces-redirect=true";
      }

      ++index;
    }

    return null;
  }

  /** If this methods returns true, only the draft button is shown. */
  public Boolean getDraftButtonOnly(String viewId) {
    return false;
  }

  /**
   * If this methods returns true, the release and draft buttons are shown. Otherwise they are not
   * shown.
   */
  public Boolean getReleaseDraftButtons() {
    return true;
  }

  public abstract String getDesignation();

  /** Override this in extending classes if the button "next" in the wizard should be disabled. */
  public Boolean disableNextButton(String viewId) {
    return false;
  }
}

src/main/java/de/samply/mdr/gui/beans/ChangeWizard.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package  de.samply.mdr.gui.beans;

import de.samply.mdr.dal.ResourceManager;
import de.samply.mdr.dal.dao.DefinitionDao;
import de.samply.mdr.dal.dao.ElementDao;
import de.samply.mdr.dal.dao.IdentifiedDao;
import de.samply.mdr.dal.dao.ScopedIdentifierHierarchyDao;
import de.samply.mdr.dal.dao.utils.Importer;
import de.samply.mdr.dal.dto.ConceptAssociation;
import de.samply.mdr.dal.dto.Definition;
import de.samply.mdr.dal.dto.IdentifiedElement;
import de.samply.mdr.dal.dto.Namespace;
import de.samply.mdr.dal.dto.ScopedIdentifier;
import de.samply.mdr.dal.jooq.Tables;
import de.samply.mdr.dal.jooq.enums.Elementtype;
import de.samply.mdr.dal.jooq.tables.pojos.UserSourceCredentials;
import de.samply.mdr.gui.BeanValidators;
import de.samply.mdr.gui.MdrElement;
import de.samply.mdr.gui.ValueDomainDto;
import de.samply.mdr.gui.WizardStep;
import de.samply.mdr.gui.beans.DataElementWizard.SearchStatus;
import de.samply.mdr.gui.exceptions.DuplicateIdentifierException;
import de.samply.mdr.gui.exceptions.ValidationException;
import de.samply.mdr.job.concepts.MdmQuery;
import de.samply.mdr.lib.AdapterDefinition;
import de.samply.mdr.lib.AdapterPermissibleValue;
import de.samply.mdr.lib.Constants.DatatypeField;
import de.samply.mdr.util.JsfUtil;
import de.samply.mdr.util.Mapper;
import de.samply.mdr.util.Message;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.jooq.DSLContext;
import org.jooq.exception.DataAccessException;

/**
 * This wizard allows *basic* changes only, for more information see the following.
 *
 * <pre>
 * * definitions and designations (also the labels for permitted values)
 * * members (for groups)
 * * members that identify the same identified item (for records)
 * * slots
 * </pre>
 *
 * @author paul
 */
@SessionScoped
@ManagedBean
public class ChangeWizard extends DataElementGroupWizard {

  private static final long serialVersionUID = 1L;

  private MdrElement element;

  private List<WizardStep> steps;

  private ValueDomainDto valueDomain;

  private SearchStatus searchStatusResponse = SearchStatus.TRUE;

  public SearchStatus getSearchStatus() {
    return searchStatusResponse;
  }

  @Override
  public String validateSlots() {
    if (element.getElement().getElementType() == Elementtype.DATAELEMENT) {
      getPossibleConceptAssociations().clear();
      searchStatusResponse = SearchStatus.TRUE;
      return BeanValidators.validateSlots(getSlots())
          ? "changeconceptAssociation?faces-redirect=true"
          : null;
    } else {
      return BeanValidators.validateSlots(getSlots())
          ? "changeverify?faces-redirect=true"
          : null;
    }
  }

  /**
   * starts searching process of concept associations in external sources, e.g. MDM-Portal
   */
  public void searchConceptAssociation() {
    try (DSLContext ctx = ResourceManager.getDslContext()) {
      List<UserSourceCredentials> userSourceCredentials =
          ctx.fetch(ctx.select()
              .from(Tables.USER_SOURCE_CREDENTIALS)
              .where(Tables.USER_SOURCE_CREDENTIALS.USER_ID.eq(getUserBean().getUserId())))
              .into(UserSourceCredentials.class);

      for (UserSourceCredentials usc : userSourceCredentials) {
        if (usc.getSourceId()
            .equals((ctx.fetchOne(Tables.SOURCE, Tables.SOURCE.NAME.eq("MDM")))
                .getId())) {
          MdmQuery mdmQuery = new MdmQuery(getUserBean().getUserId(), usc.getCredential());
          try {
            setPossibleConceptAssociations(
                mdmQuery.getCodes(getDefinitions().get(0).getDesignation(), null));
            searchStatusResponse = SearchStatus.FALSE;
          } catch (Exception e) {
            switch (e.getMessage()) {
              case "401":
                searchStatusResponse = SearchStatus.ERROR_401; // Unauthorized user
                Message.addError("errorUnauthorized");
                break;
              case "404":
                searchStatusResponse = SearchStatus.ERROR_404; // Not Found -> dead links
                Message.addError("errorNotFound");
                break;
              case "500":
                searchStatusResponse = SearchStatus.ERROR_500; // Internal Server Error
                Message.addError("errorInternalServerError");
                break;
              default:
                searchStatusResponse = SearchStatus.ERROR; // error
                Message.addError("errorOccured");
                break;
            }
          }
        }
        //TODO: if other concept sources are added, call up necessary methods here (e.g. SNOMED CT)
      }
    }
  }

  /**
   * Adds concept association from list of possible concept associations by term.
   */
  public void addConceptAssociationByTerm(String term) {
    if (getPossibleConceptAssociations().size() > 0) {
      int i = 0;
      for (ConceptAssociation ca : getPossibleConceptAssociations()) {

        if (ca.getTerm() != null && ca.getTerm().equals(term)) {
          // deletes blank concept association
          if (getConceptAssociations().size() != 0) {
            if (getConceptAssociations().get(0).getTerm().equals("")) {
              getConceptAssociations().remove(0);
            }
          }

          getConceptAssociations().add(ca);
          // deletes given concept association from list of possible concept association
          getPossibleConceptAssociations().remove(i);
          break;
        }
        i++;
      }
    }
  }

  /**
   * TODO: add javadoc.
   */
  public String validateConceptAssociation() {
    return BeanValidators.validateConceptAssociation(getConceptAssociations())
        ? "changeverify?faces-redirect=true"
        : null;
  }

  @Override
  public String validateDefinitions() {
    setStarted(true);
    if (BeanValidators.validateDefinitions(getDefinitions())) {
      switch (element.getElement().getElementType()) {
        case DATAELEMENT:
          if (valueDomain.getDatatype() == DatatypeField.LIST) {
            return "changevalidation?faces-redirect=true";
          } else {
            return "changeslots?faces-redirect=true";
          }

        case DATAELEMENTGROUP:
        case RECORD:
        default:
          return "changeassignment?faces-redirect=true";
      }
    } else {
      return null;
    }
  }

  @Override
  public Elementtype getElementType() {
    if (element != null) {
      return element.getElement().getElementType();
    } else {
      return Elementtype.DATAELEMENT;
    }
  }

  @Override
  public String finish() {
    String definitions = validateDefinitions();
    String identification = validateIdentification();
    String members = validateMembers();

    if (definitions == null || identification == null || members == null) {
      return null;
    }

    try (DSLContext ctx = ResourceManager.getDslContext()) {
      ctx.connection(c -> c.setAutoCommit(false));
      Namespace namespace = ElementDao.getNamespace(ctx, getNamespace());

      ScopedIdentifier identifier =
          super.finish(ctx, element.getElement().getId(), namespace.getId());

      if (element.getElement().getElementType() == Elementtype.DATAELEMENT) {
        if (valueDomain.getDatatype() == DatatypeField.LIST) {
          List<AdapterPermissibleValue> values = valueDomain.getPermittedValues();
          for (AdapterPermissibleValue value : values) {
            for (AdapterDefinition definition : value.getDefinitions()) {
              Definition def = Mapper.convert(definition);
              def.setElementId(value.getId());
              def.setScopedIdentifierId(identifier.getId());
              DefinitionDao.saveDefinition(ctx, def);
            }
          }
        }
      } else {
        Importer importer = new Importer();

        int index = 1;
        for (MdrElement element : getElements()) {
          ScopedIdentifier sub =
              importer.importElement(
                  ctx, element.getUrn(), identifier.getNamespace(), getUserBean().getUserId());
          ScopedIdentifierHierarchyDao
              .addSubIdentifier(ctx, identifier.getId(), sub.getId(), index++);
        }
      }
      ctx.connection(Connection::commit);
      return done();
    } catch (DuplicateIdentifierException | ValidationException e) {
      e.printStackTrace();
      return null;
    }
  }

  /**
   * Initializes this wizard for the given URN.
   */
  public String initialize(String urn) {
    try (DSLContext ctx = ResourceManager.getDslContext()) {
      element = template(ctx, urn);

      steps = new ArrayList<>();
      steps.add(
          new WizardStep(JsfUtil.getString("definitions"), 1, "/user/changedefinitions.xhtml"));

src/main/java/de/samply/mdr/gui/beans/ImportBean.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package  de.samply.mdr.gui.beans;

import de.samply.mdr.dal.ResourceManager;
import de.samply.mdr.dal.dao.utils.Importer;
import de.samply.mdr.gui.MdrElement;
import de.samply.mdr.gui.MdrNamespace;
import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.jooq.DSLContext;

/**
 * Handles the import of one element into another namespace.
 *
 * @author paul
 */
@ManagedBean
@ViewScoped
public class ImportBean implements Serializable {

  private static final long serialVersionUID = 1L;

  @ManagedProperty("#{userBean}")
  private UserBean userBean;

  /** imports the given element into the given namespace. */
  public String importElement(MdrElement element, MdrNamespace namespace) {
    Importer importer = new Importer();

    /*
     * If the namespace is not writable, abort without an error message. The user tried to do
     * something he shouldn't be able to do anyway.
     */
    if (!userBean.isWritableNamespace(namespace)) {
      return null;
    }

    try (DSLContext ctx = ResourceManager.getDslContext()) {
      return "/detail.xhtml?faces-redirect=true&urn="
          + importer.importElement(
              ctx, element.getUrn(), namespace.getName(), userBean.getUserId());
    }
  }

  public UserBean getUserBean() {
    return userBean;
  }

  public void setUserBean(UserBean userBean) {
    this.userBean = userBean;
  }
}

src/main/webapp/user/catalogverify.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/verify.xhtml">

    <ui:param name="bean" value="#{catalogWizard}"/>

    <ui:define name="afterDefinitions">

    </ui:define>
</ui:composition>

src/main/webapp/user/changeassignment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/assignment.xhtml">

    <f:metadata>
        <f:viewAction action="#{viewBean.initialize()}"/>
    </f:metadata>

    <ui:param name="bean" value="#{changeWizard}" />
    <ui:param name="title" value="#{msg.assignMembers}"/>

</ui:composition>

src/main/webapp/user/changensdefinitions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/definitions.xhtml">

    <ui:param name="bean" value="#{changeNamespaceWizard}" />

</ui:composition>

src/main/webapp/user/changeowner.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/wizard.xhtml">

    <ui:param name="bean" value="#{changeOwnerWizard}"/>

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.changeOwner}"/>
    <ui:param name="showSteps" value="false"/>

    <ui:define name="formContainer">

        <ul class="list-group">
            <li class="list-group-item list-group-item-danger">
                <h1>
                    #{msg.changeOwnerWarning}
                </h1>
            </li>
        </ul>

        <div class="col-xs-12 well">
            <div class="form-group">
                <div class="col-xs-12 select2Email">
                    <h:inputHidden value="#{changeOwnerWizard.email}" pt:style="width: 100%;" pt:class="form-control" />
                </div>
            </div>
        </div>

        <h:commandButton id="cancelBtn" action="#{changeOwnerWizard.reset}" style="display:none;"/>
        <h:commandButton id="finishBtn" action="#{changeOwnerWizard.finish}" style="display:none;"/>

        <h:outputScript>
            var globalQuery;

            $(".select2Email").find("input").select2({
                minimumInputLength: 3,
                query: function (query) {
                    $("#searchText").val(query.term);
                    $("#suggestionsButton").click();

                    globalQuery = query;
                }
            });
        </h:outputScript>
    </ui:define>

    <ui:define name="misc">
        <h:form prependId="false">
            <script>
                if(globalQuery != undefined) {
                    var data = {results: []};
                    var emails = $("#suggestionsHidden").val().split(",");
                    var i;
                    for(i = 0; i &lt; emails.length; ++i) {
                        data.results.push({id: emails[i], text: emails[i]});
                    }
                    globalQuery.callback(data);
                }
            </script>

            <h:inputHidden value="#{changeNamespaceWizard.searchText}" id="searchText" />
            <h:inputHidden value="#{changeNamespaceWizard.suggestions}" id="suggestionsHidden" />
            <h:commandButton action="#{changeNamespaceWizard.searchEmail}" value="NONE" style="display: none;" id="suggestionsButton">
                <f:ajax execute="@form" render="@form"/>
            </h:commandButton>
        </h:form>

    </ui:define>

</ui:composition>

src/main/webapp/user/changeslots.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/slots.xhtml">

    <ui:param name="bean" value="#{changeWizard}" />

</ui:composition>

src/main/webapp/user/changevalidation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/wizard.xhtml">

    <ui:param name="bean" value="#{changeWizard}"/>

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.validation}"/>

    <ui:define name="formContainer">
        <sa:valueDomain bean="#{changeWizard}" readonly="false" change="true"/>

        <h:commandButton id="cancelBtn" action="#{changeWizard.reset}" style="display:none;"/>
        <h:commandButton id="previousBtn" action="changedefinitions?faces-redirect=true" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{changeWizard.validateValidation}" style="display:none;"/>

    </ui:define>

    <ui:define name="misc">
        <h:panelGroup id="scrollFragment" layout="block">
            <script type="text/javascript">
                $('html, body').animate({
                    scrollTop: $("#wizardForm div:last").offset().top
                }, 1000);
            </script>
        </h:panelGroup>
    </ui:define>
</ui:composition>

src/main/webapp/user/changeverify.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="../components/verify.xhtml">

    <ui:param name="bean" value="#{changeWizard}"/>

    <ui:define name="afterDefinitions">
        <ui:fragment rendered="#{changeWizard.elementType == 'DATAELEMENT'}">
            <h2>#{msg.validation}</h2>
            <sa:valueDomain bean="#{changeWizard}" readonly="true"/>
        </ui:fragment>


        <ui:fragment rendered="#{changeWizard.elementType == 'DATAELEMENTGROUP' or changeWizard.elementType == 'RECORD'}">
            <h2><h:outputText value="#{msg.members}"/></h2>
            <div class="clearfix" id="elements">
                <sa:elements list="#{changeWizard.elements}" emptyText="#{msg.noMembers}"/>
            </div>
        </ui:fragment>
    </ui:define>
</ui:composition>

src/main/webapp/user/update.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="/components/default.xhtml">


    <f:metadata>
        <f:viewParam name="urn" value="#{updateBean.urn}"/>
    </f:metadata>

    <ui:param name="bodyClass" value="container" />

    <ui:define name="body">

        <h:form prependId="false">
            <h:commandButton value="NONE" id="initializeButton" style="display: none;" action="#{updateBean.initialize()}">
                <f:ajax render="updateStats"/>
            </h:commandButton>
            <h:commandButton id="updateButton" action="#{updateBean.update}" value="#{msg.executeUpdate}" style="display: none;" />
        </h:form>

        <sa:pleaseWaitModal />

        <h:panelGroup id="updateStats" styleClass="fadein" layout="block" style="display: none;">

            <h:outputScript>
                $(function() {
                    var dialog = $("#pleaseWaitDialog");
                    if(dialog.hasClass("in")) {
                        dialog.modal("hide");
                        $("#updateStats").show();
                    } else {
                        dialog.modal("show");
                        $("#initializeButton").click();
                    }
                });
            </h:outputScript>

            <div class="clearfix">
                <h1 class="col-xs-12">
                    #{msg.update} #{updateBean.element.designation} (#{updateBean.element.urn})
                </h1>
            </div>

            <ui:fragment rendered="#{! updateBean.keys.isEmpty()}">

                <table class="table table-striped table-hover col-xs-12">
                    <thead>
                        <tr>
                            <th scope="col">#{msg.oldElements}</th>
                            <th scope="col">#{msg.newElements}</th>
                        </tr>
                    </thead>

                    <tbody>

                        <ui:repeat var="e" value="#{updateBean.keys}">
                        <tr class="#{updateBean.status(e)} tableVCenter">
                            <td>
                                 #{e.definition} <br/>
                                 #{e.urn}
                            </td>

                            <td>
                                <ui:fragment rendered="#{! updateBean.isDeleted(e)}">
                                    #{updateBean.replacements.get(e).definition} <br/>
                                    #{updateBean.replacements.get(e).urn}
                                </ui:fragment>

                                <ui:fragment rendered="#{updateBean.isDeleted(e)}">
                                    Deleted
                                </ui:fragment>
                            </td>
                        </tr>
                        </ui:repeat>
                    </tbody>
                </table>

                <p>#{msg.notUpdatedIgnored}</p>

                <div class="col-xs-12">
                    <button class="btn btn-primary pull-right" onclick="$('#updateButton').click();">#{msg.executeUpdate}</button>
                </div>

            </ui:fragment>

            <ui:fragment rendered="#{updateBean.keys.isEmpty()}">
                <h3>#{msg.noUpdate}</h3>
            </ui:fragment>

        </h:panelGroup>

    </ui:define>

</ui:composition>