src/main/java/de/samply/mdr/gui/beans/ChangeWizard.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Copyright (C) since 2016 The Samply Community
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package  de.samply.mdr.gui.beans;

import de.samply.mdr.dal.ResourceManager;
import de.samply.mdr.dal.dao.DefinitionDao;
import de.samply.mdr.dal.dao.ElementDao;
import de.samply.mdr.dal.dao.IdentifiedDao;
import de.samply.mdr.dal.dao.ScopedIdentifierHierarchyDao;
import de.samply.mdr.dal.dao.utils.Importer;
import de.samply.mdr.dal.dto.ConceptAssociation;
import de.samply.mdr.dal.dto.Definition;
import de.samply.mdr.dal.dto.IdentifiedElement;
import de.samply.mdr.dal.dto.Namespace;
import de.samply.mdr.dal.dto.ScopedIdentifier;
import de.samply.mdr.dal.jooq.Tables;
import de.samply.mdr.dal.jooq.enums.Elementtype;
import de.samply.mdr.dal.jooq.tables.pojos.UserSourceCredentials;
import de.samply.mdr.gui.BeanValidators;
import de.samply.mdr.gui.MdrElement;
import de.samply.mdr.gui.ValueDomainDto;
import de.samply.mdr.gui.WizardStep;
import de.samply.mdr.gui.beans.DataElementWizard.SearchStatus;
import de.samply.mdr.gui.exceptions.DuplicateIdentifierException;
import de.samply.mdr.gui.exceptions.ValidationException;
import de.samply.mdr.job.concepts.MdmQuery;
import de.samply.mdr.lib.AdapterDefinition;
import de.samply.mdr.lib.AdapterPermissibleValue;
import de.samply.mdr.lib.Constants.DatatypeField;
import de.samply.mdr.util.JsfUtil;
import de.samply.mdr.util.Mapper;
import de.samply.mdr.util.Message;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import org.jooq.DSLContext;
import org.jooq.exception.DataAccessException;

/**
 * This wizard allows *basic* changes only, for more information see the following.
 *
 * <pre>
 * * definitions and designations (also the labels for permitted values)
 * * members (for groups)
 * * members that identify the same identified item (for records)
 * * slots
 * </pre>
 *
 * @author paul
 */
@SessionScoped
@ManagedBean
public class ChangeWizard extends DataElementGroupWizard {

  private static final long serialVersionUID = 1L;

  private MdrElement element;

  private List<WizardStep> steps;

  private ValueDomainDto valueDomain;

  private SearchStatus searchStatusResponse = SearchStatus.TRUE;

  public SearchStatus getSearchStatus() {
    return searchStatusResponse;
  }

  @Override
  public String validateSlots() {
    if (element.getElement().getElementType() == Elementtype.DATAELEMENT) {
      getPossibleConceptAssociations().clear();
      searchStatusResponse = SearchStatus.TRUE;
      return BeanValidators.validateSlots(getSlots())
          ? "changeconceptAssociation?faces-redirect=true"
          : null;
    } else {
      return BeanValidators.validateSlots(getSlots())
          ? "changeverify?faces-redirect=true"
          : null;
    }
  }

  /**
   * starts searching process of concept associations in external sources, e.g. MDM-Portal
   */
  public void searchConceptAssociation() {
    try (DSLContext ctx = ResourceManager.getDslContext()) {
      List<UserSourceCredentials> userSourceCredentials =
          ctx.fetch(ctx.select()
              .from(Tables.USER_SOURCE_CREDENTIALS)
              .where(Tables.USER_SOURCE_CREDENTIALS.USER_ID.eq(getUserBean().getUserId())))
              .into(UserSourceCredentials.class);

      for (UserSourceCredentials usc : userSourceCredentials) {
        if (usc.getSourceId()
            .equals((ctx.fetchOne(Tables.SOURCE, Tables.SOURCE.NAME.eq("MDM")))
                .getId())) {
          MdmQuery mdmQuery = new MdmQuery(getUserBean().getUserId(), usc.getCredential());
          try {
            setPossibleConceptAssociations(
                mdmQuery.getCodes(getDefinitions().get(0).getDesignation(), null));
            searchStatusResponse = SearchStatus.FALSE;
          } catch (Exception e) {
            switch (e.getMessage()) {
              case "401":
                searchStatusResponse = SearchStatus.ERROR_401; // Unauthorized user
                Message.addError("errorUnauthorized");
                break;
              case "404":
                searchStatusResponse = SearchStatus.ERROR_404; // Not Found -> dead links
                Message.addError("errorNotFound");
                break;
              case "500":
                searchStatusResponse = SearchStatus.ERROR_500; // Internal Server Error
                Message.addError("errorInternalServerError");
                break;
              default:
                searchStatusResponse = SearchStatus.ERROR; // error
                Message.addError("errorOccured");
                break;
            }
          }
        }
        //TODO: if other concept sources are added, call up necessary methods here (e.g. SNOMED CT)
      }
    }
  }

  /**
   * Adds concept association from list of possible concept associations by term.
   */
  public void addConceptAssociationByTerm(String term) {
    if (getPossibleConceptAssociations().size() > 0) {
      int i = 0;
      for (ConceptAssociation ca : getPossibleConceptAssociations()) {

        if (ca.getTerm() != null && ca.getTerm().equals(term)) {
          // deletes blank concept association
          if (getConceptAssociations().size() != 0) {
            if (getConceptAssociations().get(0).getTerm().equals("")) {
              getConceptAssociations().remove(0);
            }
          }

          getConceptAssociations().add(ca);
          // deletes given concept association from list of possible concept association
          getPossibleConceptAssociations().remove(i);
          break;
        }
        i++;
      }
    }
  }

  /**
   * TODO: add javadoc.
   */
  public String validateConceptAssociation() {
    return BeanValidators.validateConceptAssociation(getConceptAssociations())
        ? "changeverify?faces-redirect=true"
        : null;
  }

  @Override
  public String validateDefinitions() {
    setStarted(true);
    if (BeanValidators.validateDefinitions(getDefinitions())) {
      switch (element.getElement().getElementType()) {
        case DATAELEMENT:
          if (valueDomain.getDatatype() == DatatypeField.LIST) {
            return "changevalidation?faces-redirect=true";
          } else {
            return "changeslots?faces-redirect=true";
          }

        case DATAELEMENTGROUP:
        case RECORD:
        default:
          return "changeassignment?faces-redirect=true";
      }
    } else {
      return null;
    }
  }

  @Override
  public Elementtype getElementType() {
    if (element != null) {
      return element.getElement().getElementType();
    } else {
      return Elementtype.DATAELEMENT;
    }
  }

  @Override
  public String finish() {
    String definitions = validateDefinitions();
    String identification = validateIdentification();
    String members = validateMembers();

    if (definitions == null || identification == null || members == null) {
      return null;
    }

    try (DSLContext ctx = ResourceManager.getDslContext()) {
      ctx.connection(c -> c.setAutoCommit(false));
      Namespace namespace = ElementDao.getNamespace(ctx, getNamespace());

      ScopedIdentifier identifier =
          super.finish(ctx, element.getElement().getId(), namespace.getId());

      if (element.getElement().getElementType() == Elementtype.DATAELEMENT) {
        if (valueDomain.getDatatype() == DatatypeField.LIST) {
          List<AdapterPermissibleValue> values = valueDomain.getPermittedValues();
          for (AdapterPermissibleValue value : values) {
            for (AdapterDefinition definition : value.getDefinitions()) {
              Definition def = Mapper.convert(definition);
              def.setElementId(value.getId());
              def.setScopedIdentifierId(identifier.getId());
              DefinitionDao.saveDefinition(ctx, def);
            }
          }
        }
      } else {
        Importer importer = new Importer();

        int index = 1;
        for (MdrElement element : getElements()) {
          ScopedIdentifier sub =
              importer.importElement(
                  ctx, element.getUrn(), identifier.getNamespace(), getUserBean().getUserId());
          ScopedIdentifierHierarchyDao
              .addSubIdentifier(ctx, identifier.getId(), sub.getId(), index++);
        }
      }
      ctx.connection(Connection::commit);
      return done();
    } catch (DuplicateIdentifierException | ValidationException e) {
      e.printStackTrace();
      return null;
    }
  }

  /**
   * Initializes this wizard for the given URN.
   */
  public String initialize(String urn) {
    try (DSLContext ctx = ResourceManager.getDslContext()) {
      element = template(ctx, urn);

      steps = new ArrayList<>();
      steps.add(
          new WizardStep(JsfUtil.getString("definitions"), 1, "/user/changedefinitions.xhtml"));

src/main/webapp/components/2page-wizard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    template="default.xhtml">

<ui:define name="body">

    <nav class="navbar navbar-inverse navbar-fixed-bottom fadein col-xs-12">
        <h:panelGroup styleClass="#{bodyClass}" id="wizard-buttons" layout="block">

            <div class="col-xs-12">
                <h:panelGroup styleClass="pull-right" layout="block">
                    <button onclick="$('#cancelBtn').trigger('click')" class="btn btn-default">#{msg.cancel}</button>

                    <h:panelGroup layout="block" rendered="#{bean.isFirstStep(view.viewId)}">
                        <button onclick="$('#previousBtn').trigger('click')" class="btn btn-default" disabled="disabled">#{msg.previous}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{! bean.isFirstStep(view.viewId)}">
                        <button onclick="$('#previousBtn').trigger('click')" class="btn btn-default">#{msg.previous}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{! bean.isLastStep(view.viewId)}">
                        <button onclick="$('#verifyBtn').trigger('click')" class="btn btn-default btn-load">#{msg.next}</button>
                    </h:panelGroup>

                    <h:panelGroup layout="block" rendered="#{bean.isLastStep(view.viewId)}">
                        <ui:fragment rendered="#{bean.releaseDraftButtons}">
                            <button onclick="$('.status').val('draft'); $('#finishBtn').trigger('click')" class="btn btn-default btn-load">#{msg.finishAsDraft}</button>
                            <button onclick="$('.status').val('release'); $('#finishBtn').trigger('click')" class="btn btn-default btn-load">#{msg.finishAndRelease}</button>
                        </ui:fragment>
                        <ui:fragment rendered="#{! bean.releaseDraftButtons}">
                            <button onclick="$('#finishBtn').trigger('click');" class="btn btn-default btn-load">#{msg.finish}</button>
                        </ui:fragment>
                    </h:panelGroup>
                </h:panelGroup>
            </div>

        </h:panelGroup>
    </nav>

    <div id="wizard-background" class="fadein col-xs-12">
        <div id="form-background" class="#{bodyClass}"></div>
    </div>

    <div class="page-wrapper">

        <h:panelGroup styleClass="content" style="height: calc(100% - 70px); padding: 60px 15px;"
                layout="block">

            <h:panelGroup style="display: inline-block" styleClass="col-xs-12" layout="block" rendered="#{showSteps != 'false'}">
                <h1 class="wiztitle"><h:outputText value="#{bean.designation} ‒ " rendered="#{bean.designation.length() > 0}" />  #{title}</h1>

                <div class="wizard">
                    <ul class="steps">
                        <ui:repeat var="s" value="#{bean.getSteps(view.viewId)}">
                            <li class="#{s.active ? 'active' : ''} #{s.complete ? 'complete' : ''}">
                                <span class="badge #{s.active ? 'badge-info' : ''} #{s.complete ? 'badge-success' : ''}">#{s.number}</span>
                                    #{s.title}
                                <h:panelGroup styleClass="chevron" rendered="#{! s.last}"/>
                            </li>
                        </ui:repeat>
                    </ul>
                </div>
            </h:panelGroup>

            <h:panelGroup styleClass="#{formContainerClass} scrollable" layout="block">
                <h:form id="wizardForm" styleClass="form-horizontal" prependId="false" onkeypress="return event.keyCode != 13;" enctype="multipart/form-data">
                    <ui:insert name="formContainer"/>

                    <h:outputScript>
                        enableSelect2();
                    </h:outputScript>
                </h:form>
            </h:panelGroup>

            <ui:insert name="misc"/>

        </h:panelGroup>

    </div>

</ui:define>

</ui:composition>

src/main/webapp/components/default.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    class="#{htmlClass}">

<h:head>
    <title><ui:insert name="title">#{requestBean.title} MDR</ui:insert></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <ui:include src="styles.xhtml"/>

    <h:outputScript>
        var contextPath = '#{facesContext.externalContext.request.contextPath}';

        $(function() {
            enableSelect2();
        });
    </h:outputScript>

    <ui:insert name="head" />
</h:head>

<h:body styleClass="#{bodyClass}">

    <h:panelGroup styleClass="demo-ribbon-wrapper left fixed" rendered="#{! requestBean.isProduction()}">
        <div class="demo-ribbon">
            Demo
        </div>
    </h:panelGroup>

    <ui:include src="navbar.xhtml"/>

    <div class="navbar-shadow"/>

    <ui:include src="dialog.xhtml"/>

    <ui:insert name="body"/>

</h:body>
</html>

src/main/webapp/components/definitions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sa="http://xmlns.jcp.org/jsf/composite/samply"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    template="wizard.xhtml">

    <ui:param name="bodyClass" value="container" />
    <ui:param name="formContainerClass" value="col-xs-12" />
    <ui:param name="title" value="#{msg.definitions}"/>

    <ui:define name="formContainer">
        <ui:insert name="preDefinitions"/>

        <sa:definitions bean="#{bean}" readonly="false" id="definitions" scroll="true"/>

        <h:commandButton id="cancelBtn" action="#{bean.reset}" style="display:none;"/>
        <h:commandButton id="previousBtn" action="#{bean.previousStep(view.viewId)}" style="display:none;"/>
        <h:commandButton id="verifyBtn" action="#{bean.validateDefinitions}" style="display:none;"/>
    </ui:define>

    <ui:define name="misc">
        <!-- This script just scrolls to the last div block of the permitted value that has been added. -->

        <h:panelGroup id="scrollFragment" layout="block">
            <script type="text/javascript">
            scrollTo("#wizardForm div:last");
            </script>
        </h:panelGroup>
    </ui:define>

</ui:composition>

src/main/webapp/components/dialog.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

        <div class="modal fade" id="errorDialog" tabindex="-1" role="dialog" aria-labelledby="errorMessages">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span class="sr-only">Close</span>
                        </button>
                        <h4 class="modal-title" id="errorMessages">Validation errors</h4>
                    </div>
                    <div class="modal-body">
                        <span>#{msg.errors}</span>

                        <h:messages showSummary="true" showDetail="true" styleClass="list-group" errorClass="list-group-item list-group-item-danger"/>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>

            <h:outputScript>
            $(function() {
                if(#{facesContext.messageList.size()} > 0) {
                    $("#errorDialog").modal("show");
                }
            });
            </h:outputScript>
        </div>

</ui:composition>

src/main/webapp/components/search.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

        <div class="well">
            <div class="form-group">
                <h:outputLabel value="#{msg.search}" for="search" styleClass="col-xs-2 control-label"/>

                <h:panelGroup styleClass="col-xs-10" layout="block">
                    <h:inputText id="search" styleClass="form-control" value="#{searchBean.searchText}"
                        pt:placeholder="#{msg.searchPlaceholder}"/>
                </h:panelGroup>
            </div>

            <div class="form-group">
                <h:outputLabel value="#{msg.searchFor}" for="searchType" styleClass="col-xs-2 control-label" />

                <h:panelGroup class="col-xs-10" layout="block">
                    <h:selectOneRadio id="searchType" value="#{searchBean.searchType}" layout="pageDirection">
                        <f:selectItems value="#{searchBean.searchTypes}" var="t" itemLabel="#{msg[t.toString()]}" itemValue="#{t}"/>
                        <f:ajax render="@form" execute="@form"/>
                    </h:selectOneRadio>
                </h:panelGroup>
            </div>

            <ui:fragment rendered="#{searchBean.searchType == 'ELEMENTS'}">

                <div class="form-group">
                    <h:outputLabel value="#{msg.searchFor}" for="searchFor" styleClass="col-xs-2 control-label"/>

                    <h:panelGroup class="col-xs-10" layout="block">
                        <h:selectManyCheckbox id="searchFor" value="#{searchBean.selectedTypes}" layout="pageDirection">
                            <f:selectItems value="#{searchBean.types}" var="v" itemLabel="#{msg[v.toString()]}" itemValue="#{v}"/>
                        </h:selectManyCheckbox>
                    </h:panelGroup>
                </div>

                <div class="form-group">
                    <h:outputLabel value="#{msg.searchStatus}" for="searchStatus" styleClass="col-xs-2 control-label"/>

                    <h:panelGroup class="col-xs-10" id="searchStatus" layout="block">
                        <h:selectManyCheckbox value="#{searchBean.selectedStatuses}" layout="pageDirection">
                            <f:selectItems value="#{searchBean.statuses}" var="v" itemLabel="#{msg[v.toString()]}" itemValue="#{v}"/>
                        </h:selectManyCheckbox>
                    </h:panelGroup>
                </div>

            </ui:fragment>

            <h:panelGroup rendered="#{! resultTab}" styleClass="form-group" layout="block">
                <div class="col-xs-10 col-xs-offset-2">
                    <h:commandButton styleClass="btn btn-default pull-right" value="#{msg.search}" onclick="$('#wrapperResults').addClass('fadein').show();" action="#{searchBean.updateResults}">
                        <f:ajax render="searchWrapper:searchResults" execute="@form"/>
                    </h:commandButton>
                </div>
            </h:panelGroup>

            <h:panelGroup rendered="#{resultTab}" styleClass="form-group" layout="block">
                <div class="col-xs-10 col-xs-offset-2">
                    <h:commandButton styleClass="btn btn-default pull-right" value="#{msg.search}" onclick="activateDrag(); showResultTab();" action="#{searchBean.updateResults}">
                        <f:ajax render="searchWrapper:searchResults" execute="@form"/>
                    </h:commandButton>
                </div>
            </h:panelGroup>
        </div>

        <h:inputText value="#{searchBean.selectedNamespace}" styleClass="hiddenSelectedNamespace" style="display: none;"/>
        <h:commandButton action="#{searchBean.updateElements()}" styleClass="updateElementsButton" style="display: none;">
            <f:ajax render="searchWrapper:elements" execute="@form"/>
        </h:commandButton>
</ui:composition>

src/main/webapp/components/searchForm.xhtml
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">

        <div class="well">
            <h:panelGroup styleClass="form-group" layout="block" rendered="#{allSources}">
                <h:outputLabel value="#{msg.source}" for="searchSource" styleClass="col-xs-2 control-label"/>

                <h:panelGroup styleClass="col-xs-10">
                    <h:selectOneMenu id="searchSource" value="#{searchBean.source}" styleClass="form-control">
                        <f:selectItems value="#{mdr.sources}" var="source" itemLabel="#{msg[source.toString()]}" itemValue="#{source}"/>
                        <f:ajax render="@form" event="change" execute="@form"/>
                    </h:selectOneMenu>
                </h:panelGroup>
            </h:panelGroup>

            <div class="form-group">
                <h:outputLabel value="#{msg.search}" for="search" styleClass="col-xs-2 control-label"/>

                <h:panelGroup styleClass="col-xs-10" layout="block">
                    <h:inputText id="search" styleClass="form-control" value="#{searchBean.searchText}"
                        pt:placeholder="#{msg.searchPlaceholder}"/>
                </h:panelGroup>
            </div>

            <ui:fragment rendered="#{searchBean.source == 'CADSR'}">
                <h:panelGroup styleClass="form-group" layout="block">
                    <div class="col-xs-10 col-xs-offset-2">
                        <h:commandButton styleClass="btn btn-default pull-right cadsrSearch" value="#{msg.search}"
                                onclick="$('#wrapperResults').show();$('.processingWrapper').show();$('#searchWrapper\\:searchResults').hide();"
                                action="#{searchBean.updateCadsrResults}">
                        </h:commandButton>
                    </div>
                </h:panelGroup>

                <h:commandButton action="#{searchBean.loadNext()}" style="display: none" styleClass="cadsrLoadNext">
                    <f:ajax render="searchWrapper:searchResults"/>
                </h:commandButton>
            </ui:fragment>

            <ui:fragment rendered="#{searchBean.source == 'LOCALMDR'}">
                <div class="form-group">
                    <h:outputLabel value="#{msg.searchFor}" for="searchType" styleClass="col-xs-2 control-label" />

                    <h:panelGroup class="col-xs-10" layout="block">
                        <h:selectOneRadio id="searchType" value="#{searchBean.searchType}" layout="pageDirection">
                            <f:selectItems value="#{searchBean.searchTypes}" var="t" itemLabel="#{msg[t.toString()]}" itemValue="#{t}"/>
                            <f:ajax render="@form" execute="@form"/>
                        </h:selectOneRadio>
                    </h:panelGroup>
                </div>

                <ui:fragment rendered="#{searchBean.searchType == 'ELEMENTS'}">
                    <div class="form-group">
                        <h:outputLabel value="#{msg.searchFor}" for="searchFor" styleClass="col-xs-2 control-label"/>

                        <h:panelGroup class="col-xs-10" layout="block">
                            <h:selectManyCheckbox id="searchFor" value="#{searchBean.selectedTypes}" layout="pageDirection">
                                <f:selectItems value="#{searchBean.types}" var="v" itemLabel="#{msg[v.toString()]}" itemValue="#{v}"/>
                            </h:selectManyCheckbox>
                        </h:panelGroup>
                    </div>

                    <div class="form-group">
                        <h:outputLabel value="#{msg.searchStatus}" for="searchStatus" styleClass="col-xs-2 control-label"/>

                        <h:panelGroup class="col-xs-10" id="searchStatus" layout="block">
                            <h:selectManyCheckbox value="#{searchBean.selectedStatuses}" layout="pageDirection">
                                <f:selectItems value="#{searchBean.statuses}" var="v" itemLabel="#{msg[v.toString()]}" itemValue="#{v}"/>
                            </h:selectManyCheckbox>
                        </h:panelGroup>
                    </div>
                </ui:fragment>

                <ui:fragment rendered="#{! resultTab}">
                    <h:commandButton styleClass="searchSubmit" action="#{searchBean.updateResults}" style="display: none;">
                        <f:ajax render="searchWrapper:searchResults searchWrapper:namespaceForm" execute="@form" onevent="scrollToResults"/>
                    </h:commandButton>
                </ui:fragment>

                <ui:fragment rendered="#{resultTab}">
                    <h:commandButton styleClass="searchSubmit" action="#{searchBean.updateResults}" style="display: none;">
                        <f:ajax render="searchWrapper:searchResults searchWrapper:namespaceForm" execute="@form" onevent="showResultTab"/>
                    </h:commandButton>
                </ui:fragment>

                <div class="form-group">
                    <div class="col-xs-10 col-xs-offset-2">
                        <a class="btn btn-default pull-right searchSubmitWrapper" onclick="showSearchIcon(); $('.searchSubmit').click();">
                            <i class="fa fa-fw fa-spinner" id="search-spinner-icon" style="display: none;"></i> #{msg.search}
                        </a>
                    </div>
                </div>
            </ui:fragment>
        </div>

        <h:inputText value="#{searchBean.selectedNamespace}" styleClass="hiddenSelectedNamespace" style="display: none;"/>
        <h:commandButton action="#{searchBean.updateElements()}" styleClass="updateElementsButton" style="display: none;">
            <f:ajax render="searchWrapper:elements" execute="@form"/>
        </h:commandButton>

        <h:outputScript>
            $(function() {
                $("select").select2();
            });
        </h:outputScript>

        <h:outputScript target="head">
            function scrollToResults(data) {
                if(data.status == "success") {
                    $('#wrapperResults').addClass('fadein').show();
                    scrollTo('#wrapperResults');
                    hideSearchIcon();
                }
            }

            function showResultTab(data) {
                if(data.status == "success") {
                    $("#searchTabs a[href='#searchResultTab']").tab("show");
                    hideSearchIcon();
                }
            }

            function hideSearchIcon() {
                $("#search-spinner-icon").hide();
                $(".searchSubmitWrapper").removeClass("disabled");
            }

            function showSearchIcon() {
                $("#search-spinner-icon").show();
                $(".searchSubmitWrapper").addClass("disabled");
            }
        </h:outputScript>
</ui:composition>